### ISSUE TITLE
optim was repeatedly defined in for loop - train.py 

### ISSUE THREAD

**Issue by owenmx** [NaJaeMin92/pytorch_DANN#1]

**Comment by NaJaeMin92** [comment]
Thanks for you comment.
https://github.com/NaJaeMin92/pytorch_DANN/blob/b69c4ffa9ace5d9422d3fdf21f1f974fb3c653b2/train.py#L32-L37
https://github.com/NaJaeMin92/pytorch_DANN/blob/b69c4ffa9ace5d9422d3fdf21f1f974fb3c653b2/train.py#L79-L86
